### ISSUE TITLE
Image is not showing

### ISSUE THREAD

**Issue by hassadee** [VeejayAdolf-Lemita/sdi_front-end-challenge-1#1]
https://sdi-front-end-challenge-1.vercel.app/

The image is not showing (Coed: 404), could you fix that?

**Comment by VeejayAdolf-Lemita** [comment]
it's okay now sir please re visit the link thank you. Link:
https://sdi-front-end-challenge-1.vercel.app/

**Comment by VeejayAdolf-Lemita** [comment]
https://sdi-front-end-challenge-1.vercel.app/

I have fix the images sir thank you

**Comment by VeejayAdolf-Lemita** [comment]
Awesome, thanks for the update!
